# Test Workflow (Playground Action) 

name: Hello Actions

# Event bzw. Trigger wann der Workflow ausgeführt werden soll
# Push on main bzw. Pull Request closed
on:
  push:
    branches: 
      - main

  pull_request:
    types: [closed]
  

# Workflow mit mehr als einen Jobs
jobs:
  #   Single Job mit der Id = "build"
  build:
    # Runner mit dem der Job ausgeführt wird
    runs-on: ubuntu-latest
    env:
      name: Hallo Github Action

    # Steps die eine Sequenz von Aufgaben beinhalten
    steps:

    # Führ ein Shell Kommando aus. (Runner Shell)
    - name: Run a one-line script
      run: |
           echo Hello, $name!
           echo Actor: ${{github.actor}}
           echo Commited By: ${{github.event.commits[0].author.name}}

  #   Single Job mit der Id = "weather"
  weather:
    runs-on: ubuntu-latest
    steps:
    - name: Current Weather
      run: curl "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&current=temperature_2m,wind_speed_10m&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m"

  #   Single Job mit der Id = "dump"
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

  #   Single Job mit der Id = "pull_request_only"
  pull_request_only:
    
    runs-on: ubuntu-latest
    if: github.event_name=='pull_request' # Wird nur bei einem pull_request ausgeführt
    needs: build #Wird erst ausgeführt wenn Job mit der Id build lief  
    steps:
    # Führt Kommandos auf der Runner Shell aus:
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
